---
name: Container for Kanidm

# this will build regardless,
# but only push to the container registry
# when you're committing on the master branch.

"on":
  push:

jobs:
  kanidm_build:
    runs-on: ubuntu-latest
    # strategy:
      # fail-fast: false
      #matrix:
      #  target:
      #    - linux/arm64
      #    - linux/amd64
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - name: swapfileyolooooo
        run: |
          dd if=/dev/zero of="swap.img" bs=1024 count=1024
          chmod 0600 "swap.img"
          sudo mkswap "swap.img"
          sudo chown root:root swap.img
          sudo swapon "swap.img"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      -  # https://github.com/docker/login-action/#github-container-registry
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.ref == 'refs/heads/master' }}
      - name: Build and push kanidmd
        id: docker_build_kanidmd
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          # platforms: ${{matrix.target}}
          platforms: "linux/arm64,linux/amd64"
          tags: ghcr.io/kanidm/kanidmd:devel
          build-args: |
            "KANIDM_BUILD_PROFILE=container_generic"
          file: kanidmd/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
  radius_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - linux/arm64
          - linux/amd64
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -  # https://github.com/docker/login-action/#github-container-registry
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push radius
        id: docker_build_radius
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          platforms: ${{matrix.target}}
          # https://github.com/docker/build-push-action/issues/254
          tags: ghcr.io/kanidm/radius:devel
          context: ./kanidm_rlm_python/
          cache-from: type=gha
          cache-to: type=gha,mode=max
